name: Lint AutoFix Diff

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-autofix-diff:
    name: Lint AutoFix Diff
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installation
        run: npm install

      - name: AutoFix Format
        run: npm run lint:fix

      - name: Generate Diff Patch
        run: git diff > lint.patch
